### ISSUE TITLE
Lab Report 1 Feedback

### ISSUE THREAD

**Issue by Amaar-V** [ShreyaVelagala/cse15l-lab-reports#1]
Here is your feedback for Lab Report 1:

- [ ] All relevant URLs written as markdown links
  - Does not provide VSCode markdown link (although you have VSCode already, how would someone who doesn't have it download it?)
- [ ] All relevant code examples written with backticks (```)
  - Code does not have backticks (ex: `echo hi`)
- [x] All screenshots correspond to the described steps
- [ ] All titles of sections are formatted as headers or similar
  - Section titles do not use headers
- [x] Lab report is on its own page, not the index page
- [ ] Last example counts keystrokes and shows how to run remotely saving time
  - Does not count keystrokes (see lab 1 part 7)
- [x] Text is formatted in a way that was easy for grader to read

Additional comments from your grader:
**Well Done!**
A quick reminder that the purpose of these lab reports is to serve as a guide for viewers who have never done this before so try to not skip any steps, even if you have done them previously.
*Please comment on this issue if you have any questions or need clarification, thanks!*

--------

If you don't have all the checkmarks above, fix the issues described, and then submit a [regrade request on Gradescope](https://help.gradescope.com/article/8hchz9h8wh-student-regrade-request). Use this template for your regrade request:

- Link to this issue
- Link to your published lab report page

**Comment by ShreyaVelagala** [comment]
Hi, I am confused. What does backticks (```) mean? and what does VSCode markdown link mean?

**Comment by ShreyaVelagala** [comment]
Also, my section titles use headers. I don't understand why I got this point off.

**Comment by Amaar-V** [comment]
Hey, thanks for your question.

- Backticks are used for code formatting in [markdown](https://www.markdownguide.org/basic-syntax/#code), like `this`
- For the VSCode part, I would like you to link the download link for VSCode and embed it as a markdown link. A [markdown link is this](https://www.markdownguide.org/basic-syntax/#links), it is text in markdown that can be clicked and will take you to a link.
- For the headers, you need to use [markdown headers](https://www.markdownguide.org/basic-syntax/#headings) for each section of your lab report
### They look like this

Remember that you can still get full credit for this report if you fix the issues identified and submit a regrade request on gradescope. Thank you.

**Comment by ShreyaVelagala** [comment]
Do we have to state how many keystrokes we had before making the process more efficient or just state the number of keystrokes after making the process efficient?

**Comment by Amaar-V** [comment]
Just after making the process efficient.

**Comment by ShreyaVelagala** [comment]
Is there any way you could check if my regrade request went through for this lab report?

**Comment by Amaar-V** [comment]
Yes, your request did go through. I will look at regrades this weekend.

**Comment by Amaar-V** [comment]
Well Done!
